sudo: false
language: php
php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1

before_script:
    - composer install
    - mkdir -p build/logs

script: ./bin/phpunit -c app --coverage-clover build/logs/clover.xml

after_success:
  - composer require satooshi/php-coveralls
  - ./bin/coveralls -v

cache:
    directories:
        - $HOME/.composer/cache
