sudo: false
language: php
php:
    - 5.6
    - 7.0
    - 7.1

before_script:
    - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - if [[ $TRAVIS_PHP_VERSION =~ 5.[56] ]] ; then echo yes | pecl install apcu-4.0.10; fi;
    - if [[ $TRAVIS_PHP_VERSION =~ 7.* ]]; then echo 'extension = apcu.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
    - composer install
    - mkdir -p build/logs

script: ./vendor/bin/phpunit

after_success:
  - composer require satooshi/php-coveralls
  - ./vendor/bin/coveralls -v

cache:
    directories:
        - $HOME/.composer/cache