sudo: false
language: php
php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1

before_script:
    - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - if [[ $TRAVIS_PHP_VERSION =~ 5.[56] ]] ; then echo yes | pecl install apcu-4.0.10; fi;
    - if [[ $TRAVIS_PHP_VERSION = 7.* ]] ; then echo yes | pecl install apcu; fi;
    - composer install
    - mkdir -p build/logs

script: ./bin/phpunit -c app --coverage-clover build/logs/clover.xml

after_success:
  - composer require satooshi/php-coveralls
  - ./bin/coveralls -v

cache:
    directories:
        - $HOME/.composer/cache
