imports:
    - { resource: config.yml }

framework:
    validation:
        cache: validator.mapping.cache.apc
    serializer:
        cache: serializer.mapping.cache.apc
    session:
        handler_id: session_handler

doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        result_cache_driver:
            type: service
            id: result_cache

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

services:
    redis:
        class: Redis
        calls:
            - [connect, [%redis%, 6379]]

    result_cache:
        class: Doctrine\Common\Cache\RedisCache
        calls:
            - [ setRedis, [ @redis ]]
            - [ setNamespace, [ 'sm:r:' ]]
        lazy: true

    session_handler:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        arguments:
            - @redis
            - 86400
            -
                key_prefix: 'sm:s:'
        lazy: true

    projects_cache:
        class: Doctrine\Common\Cache\RedisCache
        calls:
            - [setRedis, [@redis]]
            - [ setNamespace, [ 'sm:p:' ]]
        lazy: true
